feat:add-condition-to-pvc-creation
FXinnovation/fx-terraform-module-kubernetes-grafana pull request #2
Opened 2023-04-19 19:39 UTC by vicops

2023-04-19 20:42 UTC, gladavius requested changes

2023-04-19 20:42 UTC, gladavius commented on main.tf
> +  count            = var.create_pvc ? 1 : 0
this condition should be based on the already existing variable enabled_localstorage

Basically if you want to use a local storage for grafana you will need 2 things : 
- 1 pvc
- 1 volume mount in the deployment

So these 2 resources are 2 faces of the same coin and that's why they to be based on the same condition.

Does it make sense?

2023-04-19 20:42 UTC, gladavius commented on variables.tf
> +variable "create_pvc" {
see my previous comment, this variable can be removed

2023-04-19 21:40 UTC, vicops commented on main.tf
> +  count            = var.create_pvc ? 1 : 0
Yes David. I get your point. I will still try some few things

2023-04-20 18:30 UTC, gladavius requested changes

2023-04-20 18:30 UTC, gladavius commented on main.tf
> +              claim_name = var.enabled_localstorage ? kubernetes_persistent_volume_claim.this[0].metadata.0.name : null
you don't need to add a new condition here, the dynamic block is already conditionned by this variable enabled_localstorage

2023-04-24 13:19 UTC, gladavius approved these changes

2023-04-24 20:38 UTC, merged